# Generated by Django 4.0.2 on 2022-02-23 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='poster_pics')),
                ('title', models.CharField(default='POST Title', max_length=50)),
                ('subtitle', models.CharField(default='here poster subtitle!', max_length=150)),
                ('created', models.DateField(default=datetime.datetime.now)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
