# Generated by Django 4.0.2 on 2022-02-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manohar_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='button_link',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='poster',
            name='button_title',
            field=models.CharField(default='Click Here!', max_length=15),
        ),
    ]
