# Generated by Django 4.0.2 on 2022-02-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manohar_admin', '0002_poster_button_link_poster_button_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Vol_Spon_Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.PositiveBigIntegerField(default=0)),
                ('Volunteers', models.PositiveBigIntegerField(default=0)),
                ('Sponsers', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
