# Generated by Django 4.0.2 on 2022-02-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manohar_admin', '0003_event_vol_spon_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_vol_spon_count',
            old_name='Sponsers',
            new_name='sponsers',
        ),
        migrations.RenameField(
            model_name='event_vol_spon_count',
            old_name='Volunteers',
            new_name='volunteers',
        ),
    ]
