# Generated by Django 4.0.2 on 2022-02-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manohar_admin', '0005_alter_poster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.ImageField(default='default.png', upload_to='poster_pics'),
        ),
    ]
