# Generated by Django 4.0.2 on 2022-02-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manohar_admin', '0006_alter_poster_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Event Title', max_length=50)),
                ('area', models.CharField(default='Event Title', max_length=50)),
                ('details', models.CharField(default='Event Details', max_length=300)),
            ],
        ),
    ]
