# Generated by Django 4.0.2 on 2022-02-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manohar_admin', '0007_eventschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='area',
            field=models.CharField(default='Event Area', max_length=50),
        ),
    ]
