# Generated by Django 4.0.2 on 2022-02-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manohar_admin', '0008_alter_eventschedule_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Event Title', max_length=50)),
                ('area', models.CharField(default='Event Area', max_length=50)),
                ('details', models.CharField(default='Event Details', max_length=500)),
                ('image', models.ImageField(default='default.png', upload_to='program_pics')),
            ],
        ),
    ]
