# Generated by Django 4.0.2 on 2022-02-23 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manohar_admin', '0009_programs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programs',
            new_name='Program',
        ),
    ]
