# Generated by Django 4.0.2 on 2022-02-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manohar_admin', '0011_alter_program_area_alter_program_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='default.png', upload_to='gallery_pics')),
            ],
        ),
    ]
