# Generated by Django 4.0.2 on 2022-02-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manohar_admin', '0012_gallery_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Video Title', max_length=50)),
                ('link', models.CharField(default='Past Link Here', max_length=100)),
                ('ytid', models.CharField(default='Dont Do anything here!', max_length=50)),
            ],
        ),
    ]
