# Generated by Django 4.0.2 on 2022-02-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manohar_admin', '0013_youtubevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=20)),
                ('image', models.ImageField(default='default.png', upload_to='teammates_pics')),
                ('position', models.CharField(default='position', max_length=15)),
                ('email', models.CharField(default='Email', max_length=50)),
                ('facebook', models.CharField(default='facebook-profile-link', max_length=100)),
                ('twitter', models.CharField(default='twitter-profile-link', max_length=100)),
                ('linkedin', models.CharField(default='linkedin-profile-link', max_length=100)),
            ],
        ),
    ]
