# Generated by Django 4.0.2 on 2022-02-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manohar_admin', '0014_teammate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='default.png', upload_to='media_posts')),
            ],
        ),
    ]
