# Generated by Django 4.0.2 on 2022-05-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manohar_admin', '0017_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='details',
            field=models.TextField(default='Program Details', max_length=500),
        ),
    ]
