# Generated by Django 4.0.2 on 2022-05-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manohar_admin', '0018_alter_program_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image_description',
            field=models.CharField(default='image description', max_length=10),
        ),
    ]
