# Generated by Django 4.0.2 on 2022-05-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manohar_admin', '0019_program_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='details',
            field=models.TextField(default='Program Details', max_length=1000),
        ),
        migrations.AlterField(
            model_name='program',
            name='image_description',
            field=models.CharField(default='image description', max_length=500),
        ),
    ]
