# Generated by Django 4.0.2 on 2022-05-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manohar_admin', '0020_alter_program_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='area',
            field=models.CharField(default='Event Area', max_length=50, null=True),
        ),
    ]
