# Generated by Django 4.0.2 on 2022-05-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manohar_admin', '0021_alter_eventschedule_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='areacol',
            field=models.CharField(default='Program Area Colour', max_length=50),
        ),
        migrations.AddField(
            model_name='program',
            name='detailscol',
            field=models.TextField(default='Program Details Colour', max_length=1000),
        ),
        migrations.AddField(
            model_name='program',
            name='titlecol',
            field=models.CharField(default='Program Title Colour', max_length=50),
        ),
    ]
