# Generated by Django 4.0.2 on 2022-05-13 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manohar_admin', '0023_alter_program_areacol_alter_program_detailscol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='areacol',
        ),
        migrations.RemoveField(
            model_name='program',
            name='detailscol',
        ),
        migrations.RemoveField(
            model_name='program',
            name='titlecol',
        ),
    ]
