# Generated by Django 4.0.2 on 2022-05-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manohar_admin', '0024_remove_program_areacol_remove_program_detailscol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='areacol',
            field=models.CharField(default='#000000', max_length=10),
        ),
        migrations.AddField(
            model_name='program',
            name='detailscol',
            field=models.TextField(default='#000000', max_length=10),
        ),
        migrations.AddField(
            model_name='program',
            name='titlecol',
            field=models.CharField(default='#000000', max_length=10),
        ),
    ]
