# Generated by Django 4.0.2 on 2022-05-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manohar_admin', '0026_alter_program_detailscol'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50, null=True)),
                ('fatherName', models.CharField(max_length=50, null=True)),
                ('montherName', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('conactNumber', models.PositiveBigIntegerField(null=True)),
                ('whatsApp', models.PositiveBigIntegerField(null=True)),
                ('bloodGroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=4, null=True)),
                ('presentAddress', models.TextField(max_length=250, null=True)),
                ('permenantAddress', models.TextField(max_length=250, null=True)),
                ('profession', models.CharField(max_length=75, null=True)),
                ('willing_to_serve', models.CharField(choices=[('Weekends', 'Weekends'), ('Weekdays', 'Weekdays'), ('AnyTime', 'AnyTime')], max_length=12, null=True)),
                ('interested', models.CharField(choices=[('Social Media', 'Social Media'), ('Marketing', 'Marketing'), ('Web Design', 'Web Design'), ('Fund Raising', 'Fund Raising'), ('Data Entry', 'Data Entry'), ('Poster Design', 'Poster Design'), ('Training', 'Training'), ('Social Volunteering', 'Social Volunteering'), ('Event Planning and Managing', 'Event Planning and Managing'), ('Photography', 'Photography'), ('Videography', 'Videography')], max_length=30, null=True)),
                ('specialSkills', models.CharField(max_length=100, null=True)),
                ('yourMessage', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
